import "@root/shared/styles/global.css";
import "./technician.css";

export const metadata = {
  title: "Welcome to technician",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
